name: PHPFlasher and Pest

on: ['push', 'pull_request']

jobs:
  phpflasher-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - name: Install dependencies
        run: |
          composer install
          cp .env.example .env
          php artisan key:generate

      - name: Execute tests
        run: vendor/bin/pest
